from __future__ import annotations

import hashlib
from dataclasses import dataclass
from pathlib import Path
from typing import Any


PROMPT_ID = "river_city"
TEMPLATE_VERSION = "river_city_v0.2"
DEFAULT_TEMPLATE_PATH = Path(__file__).resolve().parents[1] / "prompts" / "river_city_v0.2.txt"
NEGATIVE_PROMPT = "text, numbers, logos, stock charts, candlesticks, tickers, people in foreground"
DEFAULT_WEATHER_CONDITION = "sunny"
WEATHER_SNIPPETS = {
    "sunny": (
        "Clear dry weather localized only over the floating city-disc, with crisp visibility and clean air around the "
        "mountain, rooftops, riverbanks, and waterfall. Terrain, architecture, trees, and water remain sharply readable. "
        "The surrounding white space remains empty and unaffected, with no clouds, no rain, no sky gradient, no horizon, "
        "and no light spill."
    ),
    "cloudy": (
        "Overcast cloudy weather contained around the floating city-disc, with compact cloud layers wrapping parts of "
        "the mountain and upper city without extending beyond the world. The clouds soften the existing light and mute "
        "material contrast without changing the time of day. This is dry cloud cover only: no rain, no drizzle, no "
        "falling water from the clouds, no wet streets, and no rain streaks. The surrounding white space remains pure, "
        "empty, and unclouded."
    ),
    "rainy": (
        "Rainy weather contained within the floating city-disc, with localized rain clouds and visible rainfall over the "
        "city and mountain. Exposed non-snow surfaces darken and pick up glossy reflections across stone, glass, streets, "
        "and river edges. Mist gathers only around the mountain and waterfall, fading before it reaches the white "
        "background. The city layout remains readable and centered."
    ),
}
WINTER_RAINY_WEATHER_SNIPPET = (
    "Winter precipitation contained within the floating city-disc, with localized snow clouds and visible snowfall, "
    "sleet, and freezing mist over the city and mountain. Snow accumulation increases on "
    "rooftops, terraces, bridge edges, riverbanks, and the upper mountain, while dark open river channels, exposed "
    "stone, glass, and streets pick up cold wet reflections. Mist gathers only around the mountain and icy waterfall, "
    "fading before it reaches the white background. The city layout remains readable and centered."
)
TIME_OF_DAY_SNIPPETS = {
    "open": (
        "Early morning atmosphere localized to the floating world, with low warm light entering from one side of the "
        "composition. The city feels newly awake: long soft shadows, gentle highlights on upper towers and mountain "
        "edges, and a faint golden glow on the river and waterfall. The white background remains pure and empty, with "
        "no visible sun, horizon, or sky."
    ),
    "midday": (
        "Midday illumination localized to the floating world, with balanced overhead light and clear readability "
        "across the city, mountain, river, and waterfall. Shadows are shorter and cleaner, materials read clearly, and "
        "the whole floating world feels fully visible and active. The white background remains pure and empty, with no "
        "sky, horizon, or atmospheric spill."
    ),
    "close": (
        "Nightfall atmosphere localized to the floating world, with the scene near darkness except for illumination "
        "generated by the city itself. Windows, bridges, towers, terraces, riverfront edges, and small civic lights glow "
        "from within the disc, casting warm contained reflections onto nearby stone, glass, water, mist, and the "
        "waterfall. The mountain and outer terrain fall into deep blue-black shadow, while the river path remains "
        "readable through reflected city light. The white background remains pure and empty, with no sunset, no visible "
        "sun, no moon, no stars, no horizon, and no sky gradient."
    ),
}
MARKET_CONDITION_SNIPPETS = {
    "strong_risk_on": (
        "Within this contained world, the river and city feel forceful and expansive. The river is full, fast, and "
        "high-volume, with bright rapids, churning whitewater, small whirlpools, and broken gold reflections where it "
        "cuts through the city. The waterfall is broad and energetic as it leaves the disc. The mountain slopes and "
        "riverbanks feel warm and green, with lush trees, active terraces, and a few tiny birds contained over the "
        "city, never outside the disc silhouette. City lighting is bright and confident, with warm highlights on glass, "
        "stone, and water."
    ),
    "risk_on": (
        "Within this contained world, the river and city feel constructive and open. The river is full and clear, moving "
        "briskly with mild rapids, steady current, and warm reflections along the riverbanks. The waterfall is full and "
        "continuous as it leaves the disc. Mountain slopes and terraces feel green and warm-toned, while city lighting is "
        "broad, warm, and confident without becoming exaggerated."
    ),
    "flat": (
        "Within this contained world, the river and city feel balanced and still. The river is steady, moderate, and "
        "quiet, with a smooth surface, long muted reflections, and a consistent waterline along the banks. The waterfall "
        "leaves the disc in a clean, even sheet. City lighting is even and calm, with soft contrast, orderly "
        "architecture, and a stable, observant mood."
    ),
    "risk_off": (
        "Within this contained world, it is winter. The river and city feel cautious but still functional. The river is "
        "low, dark, and uneven, with small rapids, exposed stone banks, and broken reflections, but the water remains "
        "open and unfrozen. A light dusting of snow sits on rooftops, terraces, bridge edges, and the upper mountain, "
        "avoiding the river surface. The waterfall is narrower but continuous as it leaves the disc. City lighting is "
        "cool, restrained, and directional, with sharper shadows and fewer warm highlights."
    ),
    "strong_risk_off": (
        "Within this contained world, it is winter. The river and city feel strained and defensive. The river is shallow, "
        "turbulent, and visibly obstructed by jagged ice plates, with dark water forcing through narrow channels, harsh "
        "rapids, exposed stone banks, and shattered reflections. Snow gathers heavily on rooftops, bridges, terraces, "
        "river edges, and the upper mountain, making the city feel winterized and austere. The waterfall is fragmented "
        "and partly icy as it spills over the edge of the disc. City lighting is sparse, cold, and directional, with "
        "sharp shadows and a tense mood."
    ),
}


@dataclass(frozen=True)
class PromptResult:
    template_version: str
    positive_prompt: str
    negative_prompt: str
    prompt_id: str = PROMPT_ID
    source: str = "bundled"
    template_sha256: str | None = None
    template_s3_key: str | None = None
    active_s3_key: str | None = None


@dataclass(frozen=True)
class PromptTemplate:
    prompt_id: str
    version: str
    text: str
    source: str
    sha256: str
    template_s3_key: str | None = None
    active_s3_key: str | None = None


def bundled_prompt_template(template_path: Path = DEFAULT_TEMPLATE_PATH) -> PromptTemplate:
    text = template_path.read_text(encoding="utf-8")
    return PromptTemplate(
        prompt_id=PROMPT_ID,
        version=TEMPLATE_VERSION,
        text=text,
        source="bundled",
        sha256=sha256_text(text),
    )


def compose_prompt(state: dict[str, Any], template: PromptTemplate | None = None) -> PromptResult:
    prompt_template = template or bundled_prompt_template()
    weather = _weather_snippet(state)
    time_of_day = TIME_OF_DAY_SNIPPETS[_time_of_day(state)]
    market_condition = MARKET_CONDITION_SNIPPETS[_market_condition(state)]
    positive = prompt_template.text.format(
        weather=weather,
        time_of_day=time_of_day,
        market_condition=market_condition,
    ).strip()
    return PromptResult(
        prompt_id=prompt_template.prompt_id,
        template_version=prompt_template.version,
        positive_prompt=positive,
        negative_prompt=NEGATIVE_PROMPT,
        source=prompt_template.source,
        template_sha256=prompt_template.sha256,
        template_s3_key=prompt_template.template_s3_key,
        active_s3_key=prompt_template.active_s3_key,
    )


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _weather_condition(state: dict[str, Any]) -> str:
    weather = state.get("weather")
    raw = weather.get("condition") if isinstance(weather, dict) else weather
    if raw is None:
        raw = state.get("weather_condition", DEFAULT_WEATHER_CONDITION)
    condition = str(raw).strip().lower()
    if condition not in WEATHER_SNIPPETS:
        valid = ", ".join(sorted(WEATHER_SNIPPETS))
        raise ValueError(f"weather condition must be one of: {valid}")
    return condition


def _weather_snippet(state: dict[str, Any]) -> str:
    condition = _weather_condition(state)
    if condition == "rainy" and _market_condition(state) in {"risk_off", "strong_risk_off"}:
        return WINTER_RAINY_WEATHER_SNIPPET
    return WEATHER_SNIPPETS[condition]


def _market_condition(state: dict[str, Any]) -> str:
    mood = str(state.get("market_mood", "")).strip().lower()
    if mood not in MARKET_CONDITION_SNIPPETS:
        valid = ", ".join(sorted(MARKET_CONDITION_SNIPPETS))
        raise ValueError(f"market mood must be one of: {valid}")
    return mood


def _time_of_day(state: dict[str, Any]) -> str:
    time_of_day = state.get("time_of_day")
    raw = time_of_day.get("slot") if isinstance(time_of_day, dict) else time_of_day
    condition = str(raw or "open").strip().lower()
    if condition not in TIME_OF_DAY_SNIPPETS:
        valid = ", ".join(sorted(TIME_OF_DAY_SNIPPETS))
        raise ValueError(f"time of day must be one of: {valid}")
    return condition
